packages:
  - 'backend'
  - 'frontend'
allowBuilds:
  '@google/genai': true
  '@prisma/client': false
  '@prisma/engines': false
  argon2: true
  bcrypt: false
  esbuild: false
  msgpackr-extract: false
  prisma: false
  protobufjs: true
